### ISSUE TITLE
Adding StackView destroys layout.

### ISSUE THREAD

**Issue by hhammoud2** [mirego/PinLayout#104]
I have the following code in my ViewController class 

    // MARK: - Properties
    
    let titleView: UIView = {
        let titleView = UIView(frame: CGRect(x: 0, y: 0, width: screenSize.width, height: 70))
        titleView.translatesAutoresizingMaskIntoConstraints = false
        let backgroundColor = UIColor(red: 0x6D/255, green: 0xBC/255, blue: 0x63/255, alpha: 1.0)
        titleView.backgroundColor = backgroundColor
       
        return titleView
    }()
    let welcomeStackView : UIStackView = {
        let stackView = UIStackView(frame: CGRect(x: 0, y: 100, width: 50, height: 40))
        stackView.translatesAutoresizingMaskIntoConstraints = false
        stackView.axis = .vertical
        
        return stackView
    }()

    
    // MARK: Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        print("Up and running")
        setupBackgroundView()
    }

    // MARK: - Setup
    
    private func setupBackgroundView() {
        self.view.backgroundColor = .purple
        
        //Add subviews to main view
        self.view.addSubview(titleView)
        setupTitleView()
        
       //        self.view.addSubview(welcomeStackView)
       //        setupWelcomeView()
    }     

}

When I layout just the titleView, everything is fine and it looks like this.
![image](https://user-images.githubusercontent.com/32943140/33103542-baaede50-ced7-11e7-99c6-9870e8a52364.png)

Once I uncomment the line which adds welcomeStackView to the main view, everything seems to break and it looks like this. 
![image](https://user-images.githubusercontent.com/32943140/33103570-d50c5048-ced7-11e7-84ec-653ef054dcdd.png)

Does anyone have any idea why this is happening?

**Comment by lucdion** [comment]
Hi @hhammoud2, 

First, since you control view's from your UIViewController you must override `viewDidLayoutSubviews()` and layout your titleView in this method. See below

Second, UIStackView is based on auto layout, I've never tried it, but it may be difficult to mix manual layout with UIStackViews. But you may try to layout it in `viewDidLayoutSubviews()` and see if its content will get layouted automatically. 

```
override viewDidLayoutSubviews() {
   super.videDidLayoutSubviews()

   titleView.pin.top(topLayoutGuide.length).left().right().sizeToFit(.width)
   // UIStackView takes the remaining vertical space.
   welcomeStackView.pin.below(of: titleView)..bottom().left().right()
}
```

Please also have a look at the PinLayout example app.
