### ISSUE TITLE
sizeToFit vs. fitSize

### ISSUE THREAD

**Issue by rblalock** [mirego/PinLayout#106]
First:  LOVE this lib.  It's so awesome

Quirk I'm running in to after I tried to replace `fitSize` with the new `sizeToFit`.

With `fitSize`, I'm appropriately seeing the label move to the next line:

```
speciesTitle.pin.after(of: closeButton, aligned: .center).top().width(75%).fitSize().marginLeft(10).marginRight(10)
```

Result looks like this:  https://www.dropbox.com/s/uq3yaowpwd5wmr7/2017-12-05_08-57-57.png?dl=0

When using `sizeToFit`:

```
speciesTitle.pin.after(of: closeButton, aligned: .center).top().width(75%).marginLeft(10).marginRight(10).sizeToFit(.heightFlexible)
```

It will never allow the label to break to the next line.  Result is always this: https://www.dropbox.com/s/8zpq0kr9vg82npq/2017-12-05_08-55-27.png?dl=0

I've tried a combo of things like adding min/max height, etc.

Any ideas?

**Comment by lucdion** [comment]
Hi @rblalock, happy to know that you appreciate PinLayout 👍

In your situation, you have pinned the width to 75%, so you should call either `sizeToFit(.width)` or `sizeToFit(.widthFlexible)`.

The pin layout phrase is: "pin speciesTitle width to 75% and adjust the size to fit the pinned width".

**Comment by rblalock** [comment]
Ah.  I see.  I had read the vernacular of that wrong and assumed it was because of the height.  It works!  thanks so much.
