### ISSUE TITLE
'%' is not a postfix unary operator

### ISSUE THREAD

**Issue by mrseth01** [mirego/PinLayout#109]
I cannot get % support in my project that I installed using cocoapods. I get the error

`'%' is not a postfix unary operator`

when trying to do something like this:

`signButton.pin.bottom(60).left(10).right(10).height(50%)`

**Comment by lucdion** [comment]
Hi @mrseth01, is it possible that you didn't import PinLayout: 
```
import PinLayout
```

**Comment by mrseth01** [comment]
I'm definitely importing it because I'm using the library without issue except for when I try to put a percentage in.

**Comment by mrseth01** [comment]
Wait...you're right.

I had PinLayout imported in the AppDelegate and it seems to work across all the view controllers. When I added it the VC directly, it began working.

**Comment by lucdion** [comment]
Yeah, importing rules are quite strange using swift 😄  Sometimes you can import it once on a project, sometimes you need to import it multiple times.
