### ISSUE TITLE
Swift Compiler Warning

### ISSUE THREAD

**Issue by DazChong** [mirego/PinLayout#112]
Coordinates.swift

(Line 57)
```
Initialization of immutable value 'rect' was never used; consider replacing with assignment to '_' or removing it
```

it's minor, but this is the only warning left for my project. haha.

Thanks

**Comment by lucdion** [comment]
I've published a fix, no more warnings 😀
https://github.com/mirego/PinLayout/releases/tag/1.5.6

**Comment by DazChong** [comment]
Thanks, I'm very glad that most of the Swift library is very active.
And thank you for this awesome library! Storyboard just not suitable for dynamic UI, and bogged down XCode quickly.

Have a nice day!

**Comment by lucdion** [comment]
Thanks @DazChong for the nice comment! If you have any idea how to improve the library even more, feel free to share it.
