### ISSUE TITLE
resizing a UILabel 

### ISSUE THREAD

**Issue by Sully73** [mirego/PinLayout#117]
I'm a little confused on how to handle the layout of a UILabel that may contain 1 or 2 lines. I would like to preserve the origin and width, however just extend the height. Basically, I want to use sizeToFit(), but only apply it to the height

![group](https://user-images.githubusercontent.com/1440684/35391487-3eb4b1a6-01b5-11e8-8a52-31ba3b8da5d1.png)

**Comment by lucdion** [comment]
Hi @Sully73,
You simply need to do something like:
```
myLabel.pin.sizeToFit(.width) 
```

In the documentation related to `sizeToFit(.width)`: "If properties related to the width have been pinned (e.g: width, left & right, margins, ...), the reference width will be determined by these properties, if not the current view's width will be used."
See here for more details about sizeToFit: https://github.com/mirego/PinLayout#sizetofit

**Comment by Sully73** [comment]
ah, I see thank you. I didn't fully understand the sizeToFit method.

**Comment by lucdion** [comment]
In that case it will adjust the height to fit the current width.
