### ISSUE TITLE
Can Aspect Ratio be used with AVPlayer video player?

### ISSUE THREAD

**Issue by netgfx** [mirego/PinLayout#120]
Looking into how can I resize the view of the AVPlayerViewController to detect and resize based on video aspect ratio and my own constraints (height no larger than 50% of view or horizontal align)

So the question is can aspectRatio propety be used with video player or only images?

And if not how can I change dynamically the height constraints after I detect each video width/height?

Thanks in advance!

**Comment by lucdion** [comment]
Hi @netgfx, **aspectRatio** (and all other PinLayout's methods) can be applied to any view that inherits from UIView.

PinLayout's don't use constraints, whenever you want to change the size/position of a view, you have to re-layout your view to update either its position, size or both.

**Comment by netgfx** [comment]
So the flow would go like this: load video > get width&height > set dimensions to playerViewControler view > call view.layoutSubviews()
?

**Comment by lucdion** [comment]
Sorry, I've never used the AVPlayerViewController, but most UIViewController inherited class comes with their own UIView (UITableViewController, UICollectionViewController, ...). So it is not really easily possible to control how they layout their view (and subviews), I'm surprise that it don't correctly handle its movie aspectRatio. 

If you want to have more control you should probably use AVPlayer. See https://stackoverflow.com/a/31277658

**Comment by netgfx** [comment]
Even in the example that you send it uses `let playerViewController = AVPlayerViewController()` to contain the `AVPlayer` which is the underlying player.

In terms of PinLayout I'm mostly interested on how to change width and height dynamically. Since I found that after the movie is loaded I can get its width and height via `self.player.view.layer.visibleRect.width` & `self.player.view.layer.visibleRect.height`

So is there away to dynamically change the `.pin.height()` of that `self.player.view`? (Initially I set it to `.pin.height(50%)`

**Comment by lucdion** [comment]
You can use any PinLayout's sizing method https://github.com/mirego/PinLayout#width-height-and-size on any view, including the player.view.

You can also use the `aspectRatio` method to force the aspect ratio (https://github.com/mirego/PinLayout#aspect-ratio)

```
let movieAspectRatio = self.player.view.layer.visibleRect.width / self.player.view.layer.visibleRect.height
self.player.view.pin.width(100%).aspectRatio(movieAspectRatio)
```

**Comment by netgfx** [comment]
ok good to know, that helps.

Can I call `self.player.view.pin.width(100%).aspectRatio(movieAspectRatio)` from any part in the class or does it have to be inside the `layoutSubviews()` function?

**Comment by lucdion** [comment]
Yes, you should layout your views either from `UIView. layoutSubviews()` or `UIViewController.viewDidLayoutSubviews()`. This way when the size of your parent view change your subviews layout will be adjusted. This will also handle device orientation change.
