### ISSUE TITLE
Force coordinates to be integers

### ISSUE THREAD

**Issue by ivan-ushakov** [mirego/PinLayout#121]
With some PinLayout methods (for example when you use percents) it is possible to have non integer coordinates, like 201.12345. Would be great to have special method like `integer` or `round` to force PinLayout round all coordinates before applying them to frame.

**Comment by lucdion** [comment]
Hi @ivan-ushakov, are you sure? PinLayout adjust its coordinates. Can you give me an example showing that issue?
Thanks

**Comment by bernikowich-cedoni** [comment]
@lucdion create view with size (100, 100) and add subview in center with size (100, 1). I use something like this:
```
extension CGRect {

  var pixelIntegral: CGRect {
    let scale = UIScreen.main.scale

    var rect = self
    rect.origin.x = floor(rect.origin.x * scale) / scale
    rect.origin.y = floor(rect.origin.y * scale) / scale
    rect.size.width = ceil(rect.size.width * scale) / scale
    rect.size.height = ceil(rect.size.height * scale) / scale
    return rect
  }
}
```

**Comment by ivan-ushakov** [comment]
@lucdion 
Sorry for delay. I found this in console and decided that PinLayout allows non integer coordinates:

    :point_right: PinLayout Conflict: center(to: .bottomCenter, of: (UIImageView, Frame: (56.5, 84.0, 167.5, 0.0))) won’t be applied since it value has already been set to 160.
    (Layouted view info: Type: UILabel, Frame: (0.0, 0.0, 0.0, 0.0), Superviews: UIWindow -> UITransitionView -> MyViewImpl, Tag: 0)

    :point_right: PinLayout Conflict: center(to: .bottomCenter, of: (UIImageView, Frame: (56.5, 0.0, 167.5, 167.5))) won’t be applied since it value has already been set to 160.
    (Layouted view info: Type: UILabel, Frame: (158.387618759168, 240.070398085303, 3.22476248166336, 36.8592038293946), Superviews: UIWindow -> UITransitionView -> MyViewImpl, Tag: 0)

    :point_right: PinLayout Conflict: center(to: .bottomCenter, of: (UIImageView, Frame: (56.5, 0.0, 167.5, 167.5))) won’t be applied since it value has already been set to 160.
    (Layouted view info: Type: UILabel, Frame: (158.387618759168, 323.570398085303, 3.22476248166336, 36.8592038293946), Superviews: UIWindow -> UITransitionView -> MyViewImpl, Tag: 0)

**Comment by lucdion** [comment]
@ivan-ushakov PinLayout already to something similar to your `pixelIntegral` method above. 
After using PinLayout, the frame will only contains valid coordinates, rounded to the screen scaling. See https://github.com/mirego/PinLayout/blob/master/Sources/Impl/Coordinates.swift method `adjustRectToDisplayScale`.
