### ISSUE TITLE
How to deal with hidden views

### ISSUE THREAD

**Issue by Sully73** [mirego/PinLayout#123]
I have the following situation

```
+ -------------------------------- +
+                                  +
+                      +---+ +---+ +
+                      + A + + B + +
+                      +---+ +---+ +
+                                  +
+                                  +
+                                  +
+ -------------------------------- +
```
Subview `A` is pinned to the left of subview `B` However `B` can be hidden, in that case I would like to pin `A` to the right edge of its superview.  I’m aware of the `visibles` Filter method, but I did think it helps me in this situation unless I make a third view that is never hidden pinned to the right. 

What is the best way to deal with this situation?

**Comment by lucdion** [comment]
@Sully73 its true that `visibles` won't help you with that kind of situation, and that PinLayout don't offer a simple solution for that. 

One nice solution would be to add a method that will receives the list of views to dock at the right and call this method to layout the A and B views:
```
func dockRightVisibleViews(_ views: [UIView]) {
    ...
}
```

You could even add an extension method to PinLayout to do that:
```
extension PinLayout {
    func dockRightVisibleViews(_ views: [UIView]) {
        ...
    }
}
```

**Comment by Sully73** [comment]
yep, that works thanks!
