### ISSUE TITLE
iOS 9.3 rewrite `layoutSubviews` cause CPU 100% Usage

### ISSUE THREAD

**Issue by jiachenmu** [mirego/PinLayout#124]
![wechatimg23](https://user-images.githubusercontent.com/15812211/37506222-ce293042-2923-11e8-82cd-cdc871b04e32.jpeg)

Environment: iOS 9.3

When rewrite `layoutSubviews`

```
for _ in 0...4 {
            let v = UIView()
            centerView.addSubview(v)
        }
```

See CPU Usage...

**Comment by jiachenmu** [comment]
I found the reason。
In iOS 9.3, rewrite `layoutSubviews`, Adding a child view to child view，it will cause a infinite loop

**Comment by lucdion** [comment]
Hi @jiachenmu, `layoutSubviews()` is called everytime the view must be layouted, it is definitively not a good idea to add subviews from there.

**Comment by jiachenmu** [comment]
@lucdion  Thank you for your reply,  I have changed another way to layout my views. This bug is only iOS 9.3, but it is no problem in iOS 11.0. What a puzzling question...😅
