### ISSUE TITLE
Crash in iOS 10.2.1

### ISSUE THREAD

**Issue by ivan-ushakov** [mirego/PinLayout#130]
Why you do recursion here? I mean calling method `pinlayout_swizzled_viewWillLayoutSubviews()`? We have crash in iOS 10.2.1 on this line.

    extension UIViewController {
        @objc fileprivate func pinlayout_swizzled_viewWillLayoutSubviews() {
            if #available(iOS 11.0, tvOS 11.0, *) { assertionFailure() }

            self.pinlayout_swizzled_viewWillLayoutSubviews()
            let safeAreaInsets = UIEdgeInsets(top: topLayoutGuide.length, left: 0, bottom: bottomLayoutGuide.length, right: 0)

            // Set children safeArea up to 3 level, to limit the performance issue of computing this compatibilitySafeAreaInsets
            PinSafeArea.setViewSafeAreaInsets(view: view, insets: safeAreaInsets, recursiveLevel: 3)
        }
    }

Here is message from NewRelic:

    2018-04-10 19:25:11.620647 App[13193:5553488] NewRelic(6.2.0,0x174076780):    NRMAMethodProfiler.m:982    NRMA__beginMethod
        Unable to find instrumented method. It’s possible another framework has renamed the selector. Throwing Exception...
    2018-04-10 19:25:11.622194 App[13193:5553488] *** Terminating app due to uncaught exception ‘NRInvalidArgumentException’, reason: ’New Relic detected an unrecognized selector, ‘pinlayout_swizzled_viewWillLayoutSubviews’, sent to ‘UIViewController’. It’s possible _cmd was renamed by an unsafe method_exchangeImplementations().'
    *** First throw call stack:
    (0x18e6151b8 0x18d04c55c 0x100937c10 0x100937968 0x100937554 0x101fa91f4 0x101fa937c 0x1944c0948 0x19196e9d8 0x1919634cc 0x19196338c 0x1918e03e0 0x191907a68 0x191908488 0x18e5c20c0 0x18e5bfcf0 0x18e4ee2d8 0x19452e7b0 0x194529534 0x1001f4360 0x18d4d15b8)
    libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by lucdion** [comment]
Hi @ivan-ushakov, this is more an New Relic issue, swizzling has been used over time and it is still allowed by Apple. 

Here is a nice explanation of the problem and solution: https://github.com/mixpanel/mixpanel-iphone/issues/495

Explanation: 
"New Relic relies on _cmd system method to be the same as the original method. Most of swizzling implementations change that value and New Relic is pushing for a different approach stating that everyone is not doing it correctly. ReactiveCocoa, Aspect, Instabug, any swizzling library (e.g. JRSwizzle), etc... will have the same issue if you use New Relic. There are pros and cons with their approach and I think its worth to investigate for a third party framework like us but I don't see this happening in the coming release. "

Proposed solution: 
"New Relic has proposed to other customers to initialize their SDK after the conflicting library or disable interaction tracing:
[NewRelicAgent disableFeatures:NRFeatureFlag_InteractionTracing];
[NewRelic startWithApplicationToken:<appToken>];
"

Search on Internet and on the New Relic website (https://discuss.newrelic.com/) and you'll see that there is many issue with their method.

Maybe try to update your version of New Relic, it seems that they now have disabled this feature by default: "Dynamic-by-default method lookups for iOS development have been removed with Swift"
Ref:  https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/configuration/enable-swift-interaction-traces

**Comment by ivan-ushakov** [comment]
Thank you for quick and helpful reply. Yes, disabling of tracing helped and now it works!

**Comment by lucdion** [comment]
Hi @ivan-ushakov, see this release to fix more elegantly this issue: https://github.com/mirego/PinLayout/releases/tag/1.7.2
