### ISSUE TITLE
iOS 8 keyboard bug

### ISSUE THREAD

**Issue by dylanNew** [mirego/PinLayout#132]
When use PinLayout 1.6.0 in iOS 8, the keyboard won't response any event. 
UIViewController.viewWillLayoutSubviews swizzleMethod may have bug in iOS8

**Comment by lucdion** [comment]
Hi @dylanNew, do you have a sample that have this issue. This would help to investigate the isssue?

**Comment by lucdion** [comment]
@dylanNew, I tested this problem, and you're right, this problem occurs only on iOS 8. I will have to deactivate the support on `UIView.pin.safeArea` of iOS 8. A PR is comming

**Comment by lucdion** [comment]
@dylanNew I have updated PinLayout to handle your iOS 8 issue with the keyboard, please update to this release https://github.com/mirego/PinLayout/releases/tag/1.7.2. It should be fix your issue.
