### ISSUE TITLE
Center horizontally multi views

### ISSUE THREAD

**Issue by dqhieu** [mirego/PinLayout#137]
Hi, I have a case that I don't know how to do with PinLayout
```
+--------------------------------------------------------+
+                                                        +
+     +-------+     +------------------+                 +
+     + this  +     + this is a label  +                 +
+     + is an +     + with some text   +                 +
+     + image +     +                  +                 +
+     +-------+     +------------------+                 +
+--------------------------------------------------------+
```
Expect
```
+--------------------------------------------------------+
+                                                        +
+           +-------+     +------------------+           +
+           + this  +     + this is a label  +           +
+           + is an +     + with some text   +           +
+           + image +     +                  +           +
+           +-------+     +------------------+           +
+--------------------------------------------------------+
```

I want to center horizontally both image view and label with its superview. How can I do that?

**Comment by lucdion** [comment]
Hi @dqhieu, I don't have yet a nice solution yet, but I'm working on one that should be available in few days 🙂 

The solution for now would be to add a container (UIView) that would contains the image and the label.
```
// layout the image and the label
image.pin.top().left().size(100)
label.pin.top().after(of: image).width(200).sizeToFit(.width).marginLeft(10)

// Adjust the container width/height and centered it
container.pin.center().width(label.frame.maxX).height(max(image.frame.maxY, label.frame.maxY))
```

The solution I'm working on is to add a method `fitContent()`, using this method you could do:
``` 
image.pin.top().left().size(100)
label.pin.top().after(of: image).width(200).sizeToFit(.width).marginLeft(10)

container.pin.center().fitContent()
```

**Comment by dqhieu** [comment]
Thanks for your solution. I thought about a container view but it will make my view's hierarchy more complex. Anyway, only that solution can help me :D

**Comment by tcurdt** [comment]
Is there a better way (without a container view) yet?
This is very common case IMO.

My use case is a bit more specific (as both views have the same width).
Still would be good to know how this meant to be done.

**Comment by tcurdt** [comment]
For my very simple case I came up with

```
leftView.pin.below(of: aboveView).marginTop(20).width(150).height(30).hCenter(-150/2-10)
rightView.pin.below(of: aboveView).marginTop(20).width(150).height(30).hCenter(+150/2+10)
```

Not ideal - but it works. Still wondering about the general case.

**Comment by lucdion** [comment]
In that case, the nicest solution is still to use a container view, layout both views related to each other, and then call `wrapContent().hCenter()` on the container. See https://github.com/layoutBox/PinLayout#wrapContent

**Comment by tcurdt** [comment]
Having to resort to a container view is really not so great -  but thanks for the quick reply, @lucdion 
For my simple case I'll just stick with what I have then.
