### ISSUE TITLE
Variable row height

### ISSUE THREAD

**Issue by pableiros** [mirego/PinLayout#33]
It is possible to make an `UITableView` with variable row height of `UITableViewCell`s using `PinLayout`?

**Comment by lucmirego** [comment]
Yes, it is. You need to implement `UITableViewDelegate func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath)` and returns the cell' height. Using manual layout there is no magic, you need to compute the height of your cell using the current tableview's width. A trick you can do is:
```
func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
   // configure a temporary cell
   myTemplateCell.configure(....)
   return myTemplateCell.height(forTableViewWidth: myTableview.frame.width)
}
``` 

In your method `func height(forTableViewWidth: CGFloat)` you can simply returns the height for that specific tableview's height. You can even layout the cell using the specified width using PinLayout, and simply returns the last view in your cell (ex: `myButton.frame.maxY`)

**Comment by lucmirego** [comment]
Just to let you know, I've added an example in the Example app that shows an UITableView with variable height cells. https://github.com/mirego/PinLayout#examples_app

**Comment by pableiros** [comment]
Great !! finally I will know how to calculate the height programmatically. Thank you !!
