### ISSUE TITLE
Rotate Simulator can not update layout

### ISSUE THREAD

**Issue by hrscy** [mirego/PinLayout#34]
I use iphone 6 simulator
for example:
```
myView.pin.left(10).top(20).right(10).height(300)
```

![](http://oat16akgn.bkt.clouddn.com/Simulator%20Screen%20Shot%202017%E5%B9%B46%E6%9C%886%E6%97%A5%20%E4%B8%8B%E5%8D%882.19.17.png)

![](http://oat16akgn.bkt.clouddn.com/Simulator%20Screen%20Shot%202017%E5%B9%B46%E6%9C%886%E6%97%A5%20%E4%B8%8B%E5%8D%882.19.21.png)

**Comment by lucmirego** [comment]
You need to put PinLayout's command inside either `UIView.layoutSubviews()` or `UIViewController.viewDidLayoutSubviews()`. This way your layout will be automatically adjusted on device rotation. PinLayout is doesn't rely on auto layout, so layout must be done when the container change.
