### ISSUE TITLE
Center a view

### ISSUE THREAD

**Issue by pableiros** [mirego/PinLayout#35]
How can I center an `UIView`?
This is what I'm doing:

    class CenterView: UIView {
        let squareView = UIView()
    
        init() {
            super.init(frame: .zero)
        
            self.backgroundColor = .lightGray
            self.squareView.backgroundColor = UIColor.gray
            self.addSubview(self.squareView)
        }
    
        required init(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    
        override func layoutSubviews() {
            super.layoutSubviews()
        
            self.squareView.pin.vCenter().hCenter().width(60).height(50)
        }
    }

    class ViewController: UIViewController {
          override func loadView() {
              self.view = CenterView()
         }
    }

And this is what I get:

![captura de pantalla 2017-06-06 a la s 12 30 31](https://user-images.githubusercontent.com/5769029/26845540-fb93e8a0-4ab3-11e7-82e8-18fdc0017700.png)

**Comment by lucmirego** [comment]
You're right, sorry for that. I've implemented this method few days ago, and I didn't have the time to unit test it. Thanks for the report. This will be fixed today!

**Comment by lucmirego** [comment]
Thanks for the report @pableiros, the fix is completed and is available in the release 1.0.7. Unit test will be added today to ensure that this issue won't appear again 😄

**Comment by pableiros** [comment]
@lucmirego Thank you !!

**Comment by lucmirego** [comment]
Also @pableiros, I've forgot, you can also do `squareView.pin.center()` to center the view

**Comment by pableiros** [comment]
I have tried, but what I have to do is to have a square view positioned at the left and center vertically
