### ISSUE TITLE
Support for Apple TV

### ISSUE THREAD

**Issue by fassko** [mirego/PinLayout#45]
Would be nice to get this also for Apple TV.

**Comment by lucmirego** [comment]
Thanks. I've never did tvOS development, but I'll investigate that. 
If you'd like also, you could add the tvOS support and submit the change.

**Comment by lucmirego** [comment]
The tvOS support has been added. This was quite easy 😃
https://github.com/mirego/PinLayout/releases/tag/1.0.15
