### ISSUE TITLE
When using SPM PinLayoutImpl.swift generates 52 Errors

### ISSUE THREAD

**Issue by iminier** [mirego/PinLayout#55]
This happens because in the file we are missing 

`import UIKit`

after 

`#if os(iOS) || os(tvOS)`

**Comment by luc-dion** [comment]
Thanks, I'll fix that immediately

**Comment by iminier** [comment]
LOL I just finished and was about to submit a pull request and you beat me to it. Thanks for the super fast support.

**Comment by luc-dion** [comment]
Haha!  A new release is available (1.1.5).
Let me know if you have any comments or suggestions

**Comment by iminier** [comment]
will do. Thanks.
