### ISSUE TITLE
Constrain Subviews Within View

### ISSUE THREAD

**Issue by csimmonsbluebook** [mirego/PinLayout#61]
Is it possible to constrain a subview that is added to your view? For example, I add a subview called `container` to my `UITableViewCell` and then I add two `UILabels` to that container. Can I then constrain those two `UILabels` within the `container` as well?

Thanks

**Comment by luc-dion** [comment]
Hi @csimmonsbluebook, 

Your case is similar to the example "TableView with variable cell's height" in the Sample app. See the UITableViewCell implementation: https://github.com/mirego/PinLayout/blob/master/Example/PinLayoutSample/UI/Tests/TableViewExample/Cells/MethodCell.swift

If you pin your labels's edges, they will be automatically contained inside your `container`.

For example, these lines will the layout the 2 labels one below the other, they will use the full container's width with a margin of 10 pixels. These lines will also adjust label's height to match their text (`sizeToFit()`).
```
label1.pin.top().left().right().margin(10).sizeToFit()
label2.pin.below(of: label1).left().right().margin(10).sizeToFit()
```

Another similar solution:
```
label1.pin.top().left().width(100%).pinEdges().margin(10)
label2.pin.below(of: label1).left().width(100%).pinEdges().margin(10)
```

**Comment by csimmonsbluebook** [comment]
@luc-dion yeah that makes sense, and I was following that example. However, to the left of those labels I want to add an image and to the right of the labels I want to add text. Basically, it looks like a cell for an appointment. I've illustrated below:

<img width="595" alt="screen shot 2017-07-26 at 1 51 05 pm" src="https://user-images.githubusercontent.com/19786779/28635704-8e931726-7209-11e7-9c64-629b3d493ba1.png">

**Comment by luc-dion** [comment]
Instead of answering your question without testing it, I've implemented your view! Note that there is always multiple paths to achieve the same results. This is just one of them.

Here is the code:
```
class SampleView: UIView {
    fileprivate let container = UIView()
    fileprivate let logo = UIImageView(image: UIImage(named: "PinLayout-logo"))
    fileprivate let textLabel = UILabel()
    fileprivate let textLabel2 = UILabel()
    
    init() {
        super.init(frame: .zero)

        logo.contentMode = .scaleAspectFit
        addSubview(logo)
        
        textLabel.text = "12H00\n13h30"
        textLabel.font = .systemFont(ofSize: 14)
        textLabel.numberOfLines = 0
        textLabel.lineBreakMode = .byWordWrapping
        addSubview(textLabel)
        
        textLabel2.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore"
        textLabel2.font = .systemFont(ofSize: 14)
        textLabel2.numberOfLines = 3
        addSubview(textLabel2)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        
        let margin: CGFloat = 12
        logo.pin.top().left().bottom().size(100).align(.center).margin(margin)
        textLabel.pin.right(of: logo, aligned: .center).width(30%).margin(margin).sizeToFit()
        textLabel2.pin.right(of: textLabel, aligned: .center).right().margin(margin).sizeToFit()
    }
}
``` 

And the result:
![simulator screen shot jul 26 2017 2 12 25 pm](https://user-images.githubusercontent.com/14981341/28636572-8c9ddec6-720c-11e7-8e80-7f012959ca45.png)

![simulator screen shot jul 26 2017 2 12 29 pm](https://user-images.githubusercontent.com/14981341/28636574-90eccb36-720c-11e7-98cc-c743fa9753b5.png)

**Comment by luc-dion** [comment]
Please note that I'm also working on another project that will integrate perfectly with PinLayout that would resolve this kind of layout even more easily. Please stay tuned 🙂

**Comment by lucdion** [comment]
You can now check also my other project that resolves layouts with many views more easily: https://github.com/lucdion/FlexLayout
