### ISSUE TITLE
Question regarding reframing views

### ISSUE THREAD

**Issue by ChanchalW** [mirego/PinLayout#66]
I don't want to write a long issue again so I am attaching the link to my question.
**https://stackoverflow.com/questions/45649499/how-to-rearrange-multiple-view-programmatically**

I tried PinLayout today in my case. When I drag view its height is increasing but another view which is pinned below it is in the same position. Can you please suggest how to manage this. I don't want to manage every frame via calculation and long coding. My app can have thousands of different frames, so I need a dynamic solution for this problem. 

Thank you.

**Comment by lucdion** [comment]
@ChanchalW you need to re-layout everything when a view size or position change. Don't be afraid, it will be fast enough. 

```
func dragRecognized(_ sender : UIPanGestureRecognizer) {
        if let view = sender.view {
            // 1) Update the view property that has changed
            ....

            // 2) Relayout everything
            layoutCollage()
        }
    }
```
