### ISSUE TITLE
Why does sizeToFit() require either width or height to be specified?

### ISSUE THREAD

**Issue by antonselyanin** [mirego/PinLayout#70]
Why does sizeToFit() require either width or height to be specified?
I tried it on a label, here is what I got: 

**Width/height not specified**
```swift
nameLabel.pin.top(50).left(40).sizeToFit()
dump(nameLabel.frame)
```
```
▿ (40.0, 50.0, 0.0, 0.0)
  ▿ origin: (40.0, 50.0)
    - x: 40.0
    - y: 50.0
  ▿ size: (0.0, 0.0)
    - width: 0.0
    - height: 0.0
```

**Added width to trigger size calculation**
```swift
nameLabel.pin.top(50).height(40).left(40).sizeToFit()
dump(nameLabel.frame)
```
```
▿ (40.0, 50.0, 173.333333333333, 20.3333333333333)
  ▿ origin: (40.0, 50.0)
    - x: 40.0
    - y: 50.0
  ▿ size: (173.333333333333, 20.3333333333333)
    - width: 173.333333333333
    - height: 20.3333333333333
```

I tried to investigate what I was doing wrong, I found this test:

```swift
class AdjustSizeSpec: QuickSpec {
...

it("should adjust the size of aView by calling sizeToFit() method without having specified width and height") {
    aView.pin.sizeToFit()
    expect(aView.frame).to(equal(CGRect(x: 140.0, y: 100.0, width: 100.0, height: 60.0)))
}
...
}
```

`aView.pin.sizeToFit()` - this code can be commented out, the test still passes

There a condition in this file: PinLayoutImpl.swift, line 966
```swift
if shouldSizeToFit && (newWidth != nil || newHeight != nil) {
// ... calculate size
}
```

`(newWidth != nil || newHeight != nil)` - this condition requires either width or height to specified in order to `sizeThatFits` to be invoked.

I commented out this condition and my code `nameLabel.pin.top(50).left(40).sizeToFit()` produces the correct size.
I guess, there should be some reason for the condition to be in the code :).
Can it potentially be disabled for certain UIView subtypes like UILabel?

**Comment by lucdion** [comment]
@antonselyanin `sizeToFit()` behave like the `UIView.sizeThatFits()` method. Maybe the name is not perfect, my bad. But it requires that at least one dimension is specified (width, height, or both). 

1- In your first example, neither the height nor the width can be determined, so in that case, sizeToFit() is not applied.

2- In your second example, the height has been set 40, so sizeToFit() will update the label's size based on that information. This is equivalent of calling `nameLabel.sizeThatFits(CGSize(width: .max, height: 40)) to compute the size.

3- In the specified unit test the comment is not right, my bad again (I'll fix that). In it normal that it doesn't update the size if the width and the height haven't been specified. The comment should be: `it("should NOT adjust the size of aView if width or height has not been specified")`.

4-Finally, `sizeToFit()` exists to adjust a view's size based on either the available width or height. If in your case all you want is to adjust the label size to match its text, you should simply call `nameLabel.sizeToFit()` right after you have set label's text.

I'll update the unit test and the doc to make it clearer.

**Comment by antonselyanin** [comment]
Thanks for your explanation!

**Comment by lucdion** [comment]
@antonselyanin I have updated the documentation, sizeToFit() wasn't correctly documented. Also, I may in the near future renamed the method sizeToFit() to something else (ex: fitSize) to remove any confusion.

**Comment by lucdion** [comment]
Hi @antonselyanin, in the lastest release https://github.com/mirego/PinLayout/releases/tag/1.2.2 I have added a new method `fitSize` that replaced the now deprecated `sizeToFit` method.
