### ISSUE TITLE
[Question] Align view between to edges with margin

### ISSUE THREAD

**Issue by bolismauro** [mirego/PinLayout#72]
Suppose we have a view, and I want to vertically align the subview between the bottom and the top + 20 points. What is the best way to do it?

A really bad way would be to create another subview, set the height to 20 pixels and place it at the top of the main view. Then center the other subview between this subview bottom and the amin view bottom, but I'm sure there is a better way

**Comment by lucdion** [comment]
Hi @bolismauro, you can simply to this:
``` 
  myView.pin.top(20).bottom().align(.center)
``` 

Nice and simple 😄

**Comment by bolismauro** [comment]
so basically `align` works by aligning the view in the two previous boundaries?
(btw I guess it also needs an height)

**Comment by lucdion** [comment]
Exact. `justify()` does the same thing but horizontally.

If you don't specify a height, PinLayout will keep the view current height and center it vertically between the specified top and bottom.

**Comment by bolismauro** [comment]
nice, thanks!

**Comment by lucdion** [comment]
@bolismauro, you were right you also need to set the height, if not, the height will be resize to lay out between the top and the bottom. I've updated my first response above 😊
