### ISSUE TITLE
safeAreaLayoutGuide Support

### ISSUE THREAD

**Issue by dunqi** [mirego/PinLayout#79]
Is there an easy way to say, that the view has to be aligned to safeAreaLayoutGuide top or bottom? Couldn't find safeAreaLayoutGuide in project

**Comment by lucdion** [comment]
Hi @dunqi, please refer to this related issue https://github.com/mirego/PinLayout/issues/68.

I will update an example now that xcode 9 is official.

**Comment by lucdion** [comment]
@dunqi I've added a new method that could be useful:
`margin(_ insets: UIEdgeInsets)`
Set all margins using an UIEdgeInsets.
This method is particularly useful to set all margins using iOS 11 UIView.safeAreaInsets.

https://github.com/mirego/PinLayout/releases/tag/1.3.1
