### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by Sully73** [mirego/PinLayout#83]
First of all thanks very much for the great work. This is exactly what I was looking for, I’m building a project that involves a lot of animations and I didn’t want to be fighting with auto layout.

I did have a question. What is the best way to handle aspect ratios? Specially for UIImageViews. I’m using percent for a lot of sizing, but this makes it difficult to preserve aspect ratios.

Any suggestions?

**Comment by lucdion** [comment]
Hi @Sully73, thanks for the great comment, it's appreciated 👍 

The support of aspectRatio is on my todo list.

What will be implemented:
* Add a method `aspectRatio(:CGFloat)`. If the width or the height has been set, the aspectRatio value will be used to compute the other dimension. If neither dimension (width/height) or both have been specified, aspectRatio won't be applied and a warning will be displayed.
* Add a method `aspectRatio()` that will only work with UIImageView. This method will use the UIImageView's image aspect ratio. 

I should be able to play with this week. 

For the time being the only option I see is to layout your UIImageView in two operations:
```
let imageSize = myImageView.image!.size
let imageRatio = imageSize.width / imageSize.height

// Layout the UIImageView without specifiying the height.
myImageView.pin.top(20).left(20).width(50%)
// then adjust the height
myImageView.pin.height(myImageView.frame.width / imageRatio)
```

Soon you'll be able to do:
```
myImageView.top(20).left(20).width(50%).aspectRatio()
```

If you have any comment on my `aspectRatio` proposition just let me know 🙂

**Comment by Sully73** [comment]
What your proposing sounds great. That will handle all of my needs. Thanks

**Comment by lucdion** [comment]
Hi @Sully73, I've completed the implementation of aspectRatio, check the release 1.3.2:  https://github.com/mirego/PinLayout/releases/tag/1.3.2

**Comment by Sully73** [comment]
Thanks very much!
