### ISSUE TITLE
Widget support - 'shared' is unavailable

### ISSUE THREAD

**Issue by saltwat5r** [mirego/PinLayout#86]
Hello,
I have the following error while using PinLayout in iOS widget.

> ../Pods/PinLayout/Sources/UIView+LTR.swift:21:38: 'shared' is unavailable: Use view controller based solutions where appropriate instead.

**Comment by lucdion** [comment]
Hi @saltwat5r , the latest release should fix your issue. Thanks for reporting it!
https://github.com/mirego/PinLayout/releases/tag/1.3.3
