### ISSUE TITLE
Question: How to constrain multiple view to the height of another view?

### ISSUE THREAD

**Issue by patchthecode** [mirego/PinLayout#89]
<img width="297" alt="screen shot 2017-10-14 at 1 20 22 pm" src="https://user-images.githubusercontent.com/2439146/31579055-7d02e8ac-b0e2-11e7-85e0-d234cde65847.png">

I am trying to get the 3 labels (could be up to 4), to fit inside the height of the the profile image. I ws lost on how to do it until i read an issue that spoke about FlexLayout.

Just wondering, is FlexLayout the replacement for UIStackViews?
I'm a little confused on if i should be using FlexLayout or Pinlayout.

**Comment by patchthecode** [comment]
Also, follow-up question,
I want to create a circle ImageView

I do this by `imageView.layer.cornerRadius = imageView.frame.width / 2`
Where is the best place to do calculations based on the frame with using pin layout?
It seems that when I call the code, I am doing it before pinLayout kicks in

**Comment by lucdion** [comment]
Hi @patchthecode,

First of all, most of the time I prefer to use PinLayout because it gives me more freedom and control over how views are rendered. It is also easier to animate views.

If you have only 3 label PinLayout will do the job really easily:
```
        let imageHeight: CGFloat  = 100
        logo.pin.top().left().size(imageHeight).margin(30, 10)
        label1.pin.after(of: logo, aligned: .top).right().marginHorizontal(10).fitSize()
        label2.pin.after(of: logo, aligned: .center).right().marginHorizontal(10).fitSize()
        label3.pin.after(of: logo, aligned: .bottom).right().marginHorizontal(10).fitSize()
```

If you have more labels you need to compute label's height:
```
        let imageHeight: CGFloat  = 100
        let nbLabels: CGFloat = 4
        let labelSpacing: CGFloat = 10
        let labelHeight = (imageHeight - (nbLabels - 1) * labelSpacing) / nbLabels

        logo.pin.top().left().size(imageHeight).margin(30, 10)
        label1.pin.after(of: logo, aligned: .top).right().height(labelHeight).marginHorizontal(10)
        label2.pin.below(of: label1, aligned: .left).right().height(labelHeight).marginTop(labelSpacing).fitSize()
        label3.pin.below(of: label2, aligned: .left).right().height(labelHeight).marginTop(labelSpacing).fitSize()
        label4.pin.below(of: label3, aligned: .left).right().height(labelHeight).marginTop(labelSpacing).fitSize()
```

In this situation FlexLayout can also be a good choice. This depends on the level of control you want to have. See using FlexLayout:
```
class MainView: UIView {
    fileprivate let flexContainer = UIView()
    
    init() {
        super.init(frame: .zero)
        
        flex.addItem(flexContainer).direction(.row).define { (flex) in
            let logo = UIImageView(image: UIImage(named: "PinLayout-logo"))
            logo.layer.borderColor = UIColor.black.cgColor
            logo.layer.borderWidth = 1
            flex.addItem(logo).size(100)
            
            flex.addItem().justifyContent(.spaceBetween).height(100).marginHorizontal(10).define({ (flex) in
                addLabel("FlexLayout Label1", to: flex)
                addLabel("FlexLayout Label2", to: flex)
                addLabel("FlexLayout Label3", to: flex)
                addLabel("FlexLayout Label4", to: flex)
            })
        }
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()

        flexContainer.pin.top(100).right().marginTop(40)
        flexContainer.flex.layout(mode: .adjustHeight)
    }
    
    fileprivate func addLabel(_ text: String, to flex: Flex) {
        let label = UILabel()
        label.text = text
        label.font = .systemFont(ofSize: 14)
        flex.addItem(label)
    }
}
```

Here is the result:
<img width="275" alt="screen shot 2017-10-15 at 10 13 49 am" src="https://user-images.githubusercontent.com/14981341/31585548-a1142ae4-b191-11e7-8933-9bd2f8a2ec60.png">

**Comment by lucdion** [comment]
For your second question. PinLayout layout the view immediately, so simply need to update the `cornerRadius` immediately after.

```
        imageView.pin.top().left().size(100)
        imageView.layer.cornerRadius = imageView.frame.width / 2
```

**Comment by lucdion** [comment]
Also, yes FlexLayout can replace totally a UIStackView. It is simpler to use, much more versatile and amazingly performant.

**Comment by patchthecode** [comment]
Thank you very much for the response.
I winded up using flex.
Sometimes more control = more headache :)

I have one last question about auto-sizing cells in a UICollectionView, but let me hack at it some more. I've been trying for a while with it, but i cant seem to get it to work. I'll open a new issue for it. Thanks again man.

**Comment by lucdion** [comment]
@patchthecode simply open an issue in FlexLayout and I'll give you an answer
