### ISSUE TITLE
Use anchor then could not use margins

### ISSUE THREAD

**Issue by wjling** [mirego/PinLayout#90]
Hello. I have a question that if I have a button and pin its center to topRight of view1, but I wish to have a top margin and it seems not work. Code is below:

`button.pin.center(to: view1.anchor.topRight).marginTop(10)`

The top margin won't apply. Maybe there is another way?

**Comment by lucdion** [comment]
Hi @wjling, you're right the top margin should be applied in this situation. Sorry for that, I'll fix that today! I will also add unit tests to validate this situation.  

There are some other possible solutions, but your solution is the nicest one.

**Comment by wjling** [comment]
Thank you for your response ! Nice to hear that it will be fixed soon !

**Comment by wjling** [comment]
Same problem when I use `below` and I can't use `marginLeft` in the meantime. Something like that.

**Comment by lucdion** [comment]
@wjling, using this new release, margins are now applied to vCenter and hCenter: https://github.com/mirego/PinLayout/releases/tag/1.4.0

For your last comment, the issue was while using `below(of: view, aligned: .center)`?

**Comment by wjling** [comment]
@lucdion  Yes, I use `below(of: view, aligned: .center)` and I want a marginLeft from center

**Comment by lucdion** [comment]
@wjling it should work with the new release.

**Comment by wjling** [comment]
OK, good job! I will try them tomorrow

**Comment by wjling** [comment]
It works !

**Comment by wjling** [comment]
I have another question. I have a `viewA` and a `labelB` and I want `labelB` to be below `viewA` and `labelB`'s max width is the same as `viewA`'s width. What I want is like this:
![pasted image at 2017_10_20 03_46 pm](https://user-images.githubusercontent.com/4201777/31810604-030b92ba-b542-11e7-8f1e-8f98254c45b3.png)

And my code is:
`labelB.pin.top(to: viewA.edge.bottom).left(to: viewA.edge.left).right(to: viewA.edge.right).fitSize()`

But what I got is this:

![image](https://user-images.githubusercontent.com/4201777/31810719-6d9534ba-b542-11e7-9b98-4ab1f26fb574.png)

Any help?

**Comment by lucdion** [comment]
@wjling fitSize() ensure that the view size is not wider (or taller) than the available space, but it the view sizeThatFit() method returns a smaller width (or height), PinLayout won't change the size result.

In your case, you must use `justify(.center)` to center the label below your view A. 
Maybe I could add a parameter to fitSize() that could force the view size to be equal to the specified size even if the view's sizeThatFit() returns a smaller size.

Another possible solution for your case:
```
labelB.pin.below(of: viewA, aligned: .center).width(of: viewA).fitSize()
```

**Comment by wjling** [comment]
Thank you for your help~

**Comment by lucdion** [comment]
In your last example @wjling, you could have done also:
```
labelB.pin.below(of: viewA, aligned: .center).width(of: viewA).minWidth(viewA.frame.width).fitSize()
```
