### ISSUE TITLE
Animation transform scale not centered

### ISSUE THREAD

**Issue by kruyvanna** [mirego/PinLayout#97]
When position using left/right (not center),
when apply transform, the anchor is not centered.

        let button = UIButton()	
        button.backgroundColor = UIColor.black

        addSubview(button)
        button.pin
            .width(90%)
            .height(44)
        
        button.pin
            .marginTop(80)
            .top(10%)
            .left(10%)
                            
        
        button.transform = CGAffineTransform(scaleX: 1.5, y: 1.5)

**Comment by lucdion** [comment]
Hi @kruyvanna, it not easy to answer your issue without the complete source code. 

PinLayout position UIViews using their frame property. Updating the view transform doesn't change the view's frame. See https://developer.apple.com/documentation/uikit/uiview/1622459-transform. 

You should try to resize the button my modifying its frame and not by applying a transform.

**Comment by kruyvanna** [comment]
Hi @lucdion,
Thanks for the explanation. 
It thought the transform was applied incorrectly but that's a visual error.
I added the background color to see how the whole view transform and it works as expected.

Thanks for the great work!

**Comment by lucdion** [comment]
Good @kruyvanna! Thanks
