### ISSUE TITLE
Can not try in Xcode Playground

### ISSUE THREAD

**Issue by muukii** [mirego/PinLayout#98]
I've tried PinLayout in Xcode Playground.
But, It does not work.
You know, PinLayout run layout on deinit themselves.
But, it seems like `deinit` of `PinLayout` is different from normal application.

I tried this project.
https://cl.ly/3Q0H1h2e2D2H

![image 2017-11-13 at 22 38 19 public](https://user-images.githubusercontent.com/1888355/32728390-7a53e96e-c8c3-11e7-9656-caf3110c4ecc.png)

**Comment by lucdion** [comment]
Hi @muukii, I've tested your playground using Xcode 9.1, and it works as expected. What is the result of your test?

![simulator screen shot - iphone 8 plus - 2017-11-13 at 08 57 15](https://user-images.githubusercontent.com/14981341/32729238-1481536e-c851-11e7-843e-e8c84d499702.png)

**Comment by muukii** [comment]
@lucdion 
Oh, I'm sorry.
Please, can you open `MyPlayground.xcplayground`?

**Comment by lucdion** [comment]
@muukii you're right, objects are not released from memory in a playground as they are in a real app. Objects are kept in memory much longer, which cause this issues with PinLayout. 

One solution would be to add a method `layout()` that would force the view's layout immediately, instead of automatically trigger it on the object deletion. 

Ex: `view.pin.top().hCenter().layout()` 

But I don't like the fact that this method would have to be called only in Playgrounds.

**Comment by muukii** [comment]
@lucdion 

> But I don't like the fact that this method would have to be called only in Playgrounds.

yeah, I think so too.

But, Are the timing of releasing objects in a real app guaranteed?
If ARC or Swift has a bit chance that objects are not released, I think we should think the solution.


```
view.pin.top().hCenter().layout()
```

or 

```
define([
  aView.pin.top(),
  bView.pin.top(),
  cView.pin.top(),
])
```

**Comment by lucdion** [comment]
It would probably break many apps, but you'right @muukii, there is no guarantee that the release timing won't change in the future. 

My proposition to support playgrounds (or any change in release timing) would be:

1. Add a `layout()` method that could be **optionally** called.
2. By default, no warnings would be displayed if the `layout()` method hasn't been called. But it would be possible to activate a warning by setting to true the property `Pin.warnMissingLayoutCall`. This would remind developers to call `layout()`.

Comments?

**Comment by muukii** [comment]
@lucdion 

Your proposition is good.

And, I think we can check broken layout.

- Layout must be executed main-thread. So, on serial-queue.
- We can find not executed PinLayout by has pending PinLayout object Internally (weak var).

**Comment by lucdion** [comment]
@muukii I've added changes we've talked about in https://github.com/mirego/PinLayout/releases/tag/1.5.1.

**Comment by muukii** [comment]
@lucdion That's awesome! Thank you!
